FROM node:lts-alpine

# Vue CLI
RUN npm install -g @vue/cli

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

COPY . .

EXPOSE 8080
CMD [ "npm", "run", "serve" ]
