version: '3'
services:
  bdweb-app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - './src:/app/src'
      - './tests:/app/tests'
      - './public:/app/public'
    ports:
      - "8080:8080"

